In [9]:
import pandas as pd

df = pd.read_csv('us-counties-5_20.csv')

In [3]:
df.head()

         date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1       0
1  2020-01-22  Snohomish  Washington  53061.0      1       0
2  2020-01-23  Snohomish  Washington  53061.0      1       0
3  2020-01-24       Cook    Illinois  17031.0      1       0
4  2020-01-24  Snohomish  Washington  53061.0      1       0

In [4]:
state = df.groupby("state")
state.get_group("Georgia").set_index("date").head()

            county    state     fips  cases  deaths
date
2020-03-02  Fulton  Georgia  13121.0      2       0
2020-03-03  Fulton  Georgia  13121.0      2       0
2020-03-04  Fulton  Georgia  13121.0      2       0
2020-03-05  Fulton  Georgia  13121.0      2       0
2020-03-06  Fulton  Georgia  13121.0      2       0

In [5]:
state.get_group("Georgia").set_index("date")

               county    state     fips  cases  deaths
date
2020-03-02     Fulton  Georgia  13121.0      2       0
2020-03-03     Fulton  Georgia  13121.0      2       0
2020-03-04     Fulton  Georgia  13121.0      2       0
2020-03-05     Fulton  Georgia  13121.0      2       0
2020-03-06     Fulton  Georgia  13121.0      2       0
...               ...      ...      ...    ...     ...
2020-05-18  Whitfield  Georgia  13313.0    188       7
2020-05-18     Wilcox  Georgia  13315.0     95      12
2020-05-18     Wilkes  Georgia  13317.0     30       1
2020-05-18  Wilkinson  Georgia  13319.0     45       3
2020-05-18      Worth  Georgia  13321.0    197      17

[8889 rows x 5 columns]

In [12]:
#dc  = date change
dc =  pd.DataFrame()

for name, group in df.groupby("state"):
    if dc.empty:
        dc  = group.set_index("date")[["cases"]].rename(columns={'cases':name})
    else:
        dc  = dc.join(group.set_index("date"))[["cases"]].rename(columns={'cases':name})
            
dc.head()

MemoryError: